name: Service testing action

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build the docker-compose stack
        run: docker-compose -f tests_runner/docker-compose.yml up -d

      - name: Sleep for a minute
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Check running containers
        run: docker ps -a

      - name: Print out logs to help with debugging
        run: docker-compose -f ./tests_runner/docker-compose.yml logs

      - name: Test partition service
        run: go test  ./...

      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1 .

      - name: Build dockerimage and push to ghcr
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: antinvestor
          password: ${{ secrets.PAT }}
          repository: antinvestor/service-partition
          tags: latest