name: Service testing action

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout new code for testing
        uses: actions/checkout@v3
      - name: Setup go testing infrastructure
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build the docker-compose stack
        run: docker-compose -f "tests_runner/docker-compose.yml" up -d --build

      - name: Wait for postgresql to come up
        run: count=0; while ! nc -z localhost 5423 && [[ count -lt 30 ]]; do (( count += 1 )); sleep 1; echo "waiting for postgresql $count"; done;

      - name: Wait for keto to come up
        run: count=0; while ! nc -z localhost 4467 && [[ count -lt 20 ]]; do (( count += 1 )); sleep 1; echo "waiting for keto $count"; done;

      - name: Wait for hydra to come up
        run: count=0; while ! nc -z localhost 4445 && [[ count -lt 20 ]]; do  (( count += 1 )); sleep 1; echo "waiting for hydra $count"; done;

      - name: Allow 10 seconds for migrations to complete if any
        run: sleep 15s

      - name: Print out logs to help with debugging
        run: docker-compose -f ./tests_runner/docker-compose.yml logs

      - name: Test partition service
        run: go test  ./...

      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1 .

      - name: Stop containers
        run: docker-compose -f "tests_runner/docker-compose.yml" down
