name: Service testing action

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build the docker-compose stack
        run: docker-compose -f tests_runner/docker-compose.yml up -d
      - name: Wait for afew seconds
        run: sleep 5
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker-compose -f ./tests_runner/docker-compose.yml logs

      - name: Test With Coverage
        run: go test -v  -json ./... > test.json

      - name: Annotate tests
        uses: guyarb/golang-test-annotations@v0.3.0
        with:
          test-results: test.json

      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1 .
